apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector: {}
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ui
          image: ghcr.io/zoomoid/bucket-browser/ui:latest
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/templates
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: nginx-config
          configMap:
            name: worker-nginx-config
