apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: ui
configMapGenerator:
  - name: worker-nginx-config
    options:
      disableNameSuffixHash: true
    files:
      - default.conf.template
