apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector: {}
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: ghcr.io/zoomoid/bucket-browser/worker:latest
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: worker-env
          ports:
            - containerPort: 3000
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          